name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          configPath: './tauri.conf.json' # Tauri配置文件的路径
          distPath: './dist' # Vite应用的输出目录
          iconPath: './src-tauri/icons' # 应用图标的路径
